global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'histoscan_ai'
    static_configs:
      - targets: ['histoscanapp67890.centralindia.azurecontainer.io:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s